// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: bsdiff/bsdiff.proto

package bsdiff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Control is a bsdiff operation, see https://twitter.com/fasterthanlime/status/790617515009437701
type Control struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Add           []byte                 `protobuf:"bytes,1,opt,name=add,proto3" json:"add,omitempty"`
	Copy          []byte                 `protobuf:"bytes,2,opt,name=copy,proto3" json:"copy,omitempty"`
	Seek          int64                  `protobuf:"varint,3,opt,name=seek,proto3" json:"seek,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"` // when true, don't apply and stop reading bsdiff control
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_bsdiff_bsdiff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_bsdiff_bsdiff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_bsdiff_bsdiff_proto_rawDescGZIP(), []int{0}
}

func (x *Control) GetAdd() []byte {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *Control) GetCopy() []byte {
	if x != nil {
		return x.Copy
	}
	return nil
}

func (x *Control) GetSeek() int64 {
	if x != nil {
		return x.Seek
	}
	return 0
}

func (x *Control) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

var File_bsdiff_bsdiff_proto protoreflect.FileDescriptor

const file_bsdiff_bsdiff_proto_rawDesc = "" +
	"\n" +
	"\x13bsdiff/bsdiff.proto\x12\x14io.itch.wharf.bsdiff\"U\n" +
	"\aControl\x12\x10\n" +
	"\x03add\x18\x01 \x01(\fR\x03add\x12\x12\n" +
	"\x04copy\x18\x02 \x01(\fR\x04copy\x12\x12\n" +
	"\x04seek\x18\x03 \x01(\x03R\x04seek\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eofB Z\x1egithub.com/itchio/wharf/bsdiffb\x06proto3"

var (
	file_bsdiff_bsdiff_proto_rawDescOnce sync.Once
	file_bsdiff_bsdiff_proto_rawDescData []byte
)

func file_bsdiff_bsdiff_proto_rawDescGZIP() []byte {
	file_bsdiff_bsdiff_proto_rawDescOnce.Do(func() {
		file_bsdiff_bsdiff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bsdiff_bsdiff_proto_rawDesc), len(file_bsdiff_bsdiff_proto_rawDesc)))
	})
	return file_bsdiff_bsdiff_proto_rawDescData
}

var file_bsdiff_bsdiff_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bsdiff_bsdiff_proto_goTypes = []any{
	(*Control)(nil), // 0: io.itch.wharf.bsdiff.Control
}
var file_bsdiff_bsdiff_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bsdiff_bsdiff_proto_init() }
func file_bsdiff_bsdiff_proto_init() {
	if File_bsdiff_bsdiff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bsdiff_bsdiff_proto_rawDesc), len(file_bsdiff_bsdiff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bsdiff_bsdiff_proto_goTypes,
		DependencyIndexes: file_bsdiff_bsdiff_proto_depIdxs,
		MessageInfos:      file_bsdiff_bsdiff_proto_msgTypes,
	}.Build()
	File_bsdiff_bsdiff_proto = out.File
	file_bsdiff_bsdiff_proto_goTypes = nil
	file_bsdiff_bsdiff_proto_depIdxs = nil
}
