// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pwr/overlay/overlay.proto

package overlay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverlayOp_Type int32

const (
	OverlayOp_SKIP           OverlayOp_Type = 0
	OverlayOp_FRESH          OverlayOp_Type = 1
	OverlayOp_HEY_YOU_DID_IT OverlayOp_Type = 2040
)

// Enum value maps for OverlayOp_Type.
var (
	OverlayOp_Type_name = map[int32]string{
		0:    "SKIP",
		1:    "FRESH",
		2040: "HEY_YOU_DID_IT",
	}
	OverlayOp_Type_value = map[string]int32{
		"SKIP":           0,
		"FRESH":          1,
		"HEY_YOU_DID_IT": 2040,
	}
)

func (x OverlayOp_Type) Enum() *OverlayOp_Type {
	p := new(OverlayOp_Type)
	*p = x
	return p
}

func (x OverlayOp_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OverlayOp_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pwr_overlay_overlay_proto_enumTypes[0].Descriptor()
}

func (OverlayOp_Type) Type() protoreflect.EnumType {
	return &file_pwr_overlay_overlay_proto_enumTypes[0]
}

func (x OverlayOp_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OverlayOp_Type.Descriptor instead.
func (OverlayOp_Type) EnumDescriptor() ([]byte, []int) {
	return file_pwr_overlay_overlay_proto_rawDescGZIP(), []int{1, 0}
}

type OverlayHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverlayHeader) Reset() {
	*x = OverlayHeader{}
	mi := &file_pwr_overlay_overlay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverlayHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverlayHeader) ProtoMessage() {}

func (x *OverlayHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pwr_overlay_overlay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverlayHeader.ProtoReflect.Descriptor instead.
func (*OverlayHeader) Descriptor() ([]byte, []int) {
	return file_pwr_overlay_overlay_proto_rawDescGZIP(), []int{0}
}

type OverlayOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          OverlayOp_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=io.itch.wharf.pwr.overlay.OverlayOp_Type" json:"type,omitempty"`
	Len           int64                  `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverlayOp) Reset() {
	*x = OverlayOp{}
	mi := &file_pwr_overlay_overlay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverlayOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverlayOp) ProtoMessage() {}

func (x *OverlayOp) ProtoReflect() protoreflect.Message {
	mi := &file_pwr_overlay_overlay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverlayOp.ProtoReflect.Descriptor instead.
func (*OverlayOp) Descriptor() ([]byte, []int) {
	return file_pwr_overlay_overlay_proto_rawDescGZIP(), []int{1}
}

func (x *OverlayOp) GetType() OverlayOp_Type {
	if x != nil {
		return x.Type
	}
	return OverlayOp_SKIP
}

func (x *OverlayOp) GetLen() int64 {
	if x != nil {
		return x.Len
	}
	return 0
}

func (x *OverlayOp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pwr_overlay_overlay_proto protoreflect.FileDescriptor

const file_pwr_overlay_overlay_proto_rawDesc = "" +
	"\n" +
	"\x19pwr/overlay/overlay.proto\x12\x19io.itch.wharf.pwr.overlay\"\x0f\n" +
	"\rOverlayHeader\"\xa2\x01\n" +
	"\tOverlayOp\x12=\n" +
	"\x04type\x18\x01 \x01(\x0e2).io.itch.wharf.pwr.overlay.OverlayOp.TypeR\x04type\x12\x10\n" +
	"\x03len\x18\x02 \x01(\x03R\x03len\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"0\n" +
	"\x04Type\x12\b\n" +
	"\x04SKIP\x10\x00\x12\t\n" +
	"\x05FRESH\x10\x01\x12\x13\n" +
	"\x0eHEY_YOU_DID_IT\x10\xf8\x0fB%Z#github.com/itchio/wharf/pwr/overlayb\x06proto3"

var (
	file_pwr_overlay_overlay_proto_rawDescOnce sync.Once
	file_pwr_overlay_overlay_proto_rawDescData []byte
)

func file_pwr_overlay_overlay_proto_rawDescGZIP() []byte {
	file_pwr_overlay_overlay_proto_rawDescOnce.Do(func() {
		file_pwr_overlay_overlay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pwr_overlay_overlay_proto_rawDesc), len(file_pwr_overlay_overlay_proto_rawDesc)))
	})
	return file_pwr_overlay_overlay_proto_rawDescData
}

var file_pwr_overlay_overlay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pwr_overlay_overlay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pwr_overlay_overlay_proto_goTypes = []any{
	(OverlayOp_Type)(0),   // 0: io.itch.wharf.pwr.overlay.OverlayOp.Type
	(*OverlayHeader)(nil), // 1: io.itch.wharf.pwr.overlay.OverlayHeader
	(*OverlayOp)(nil),     // 2: io.itch.wharf.pwr.overlay.OverlayOp
}
var file_pwr_overlay_overlay_proto_depIdxs = []int32{
	0, // 0: io.itch.wharf.pwr.overlay.OverlayOp.type:type_name -> io.itch.wharf.pwr.overlay.OverlayOp.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pwr_overlay_overlay_proto_init() }
func file_pwr_overlay_overlay_proto_init() {
	if File_pwr_overlay_overlay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pwr_overlay_overlay_proto_rawDesc), len(file_pwr_overlay_overlay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pwr_overlay_overlay_proto_goTypes,
		DependencyIndexes: file_pwr_overlay_overlay_proto_depIdxs,
		EnumInfos:         file_pwr_overlay_overlay_proto_enumTypes,
		MessageInfos:      file_pwr_overlay_overlay_proto_msgTypes,
	}.Build()
	File_pwr_overlay_overlay_proto = out.File
	file_pwr_overlay_overlay_proto_goTypes = nil
	file_pwr_overlay_overlay_proto_depIdxs = nil
}
