// Code generated by protoc-gen-go.
// source: pwr/recipe.proto
// DO NOT EDIT!

/*
Package pwr is a generated protocol buffer package.

It is generated from these files:
	pwr/recipe.proto

It has these top-level messages:
	RecipeHeader
	RepoInfo
	RsyncSignatureHeader
	RsyncBlockHash
	RsyncOp
	Hash
*/
package pwr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type HashType int32

const (
	// librsync default
	HashType_MD5 HashType = 0
	// cf. https://godoc.org/golang.org/x/crypto/sha3
	HashType_SHAKESUM128 HashType = 1
)

var HashType_name = map[int32]string{
	0: "MD5",
	1: "SHAKESUM128",
}
var HashType_value = map[string]int32{
	"MD5":         0,
	"SHAKESUM128": 1,
}

func (x HashType) String() string {
	return proto.EnumName(HashType_name, int32(x))
}
func (HashType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RecipeHeader_Version int32

const (
	RecipeHeader_V1 RecipeHeader_Version = 0
)

var RecipeHeader_Version_name = map[int32]string{
	0: "V1",
}
var RecipeHeader_Version_value = map[string]int32{
	"V1": 0,
}

func (x RecipeHeader_Version) String() string {
	return proto.EnumName(RecipeHeader_Version_name, int32(x))
}
func (RecipeHeader_Version) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type RecipeHeader_Compression int32

const (
	RecipeHeader_UNCOMPRESSED RecipeHeader_Compression = 0
	RecipeHeader_BROTLI       RecipeHeader_Compression = 1
)

var RecipeHeader_Compression_name = map[int32]string{
	0: "UNCOMPRESSED",
	1: "BROTLI",
}
var RecipeHeader_Compression_value = map[string]int32{
	"UNCOMPRESSED": 0,
	"BROTLI":       1,
}

func (x RecipeHeader_Compression) String() string {
	return proto.EnumName(RecipeHeader_Compression_name, int32(x))
}
func (RecipeHeader_Compression) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type RsyncOp_Type int32

const (
	RsyncOp_BLOCK          RsyncOp_Type = 0
	RsyncOp_BLOCK_RANGE    RsyncOp_Type = 1
	RsyncOp_DATA           RsyncOp_Type = 2
	RsyncOp_HEY_YOU_DID_IT RsyncOp_Type = 2049
)

var RsyncOp_Type_name = map[int32]string{
	0:    "BLOCK",
	1:    "BLOCK_RANGE",
	2:    "DATA",
	2049: "HEY_YOU_DID_IT",
}
var RsyncOp_Type_value = map[string]int32{
	"BLOCK":          0,
	"BLOCK_RANGE":    1,
	"DATA":           2,
	"HEY_YOU_DID_IT": 2049,
}

func (x RsyncOp_Type) String() string {
	return proto.EnumName(RsyncOp_Type_name, int32(x))
}
func (RsyncOp_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type RecipeHeader struct {
	Version          RecipeHeader_Version     `protobuf:"varint,1,opt,name=version,enum=io.itch.wharf.pwr.RecipeHeader_Version" json:"version,omitempty"`
	Compression      RecipeHeader_Compression `protobuf:"varint,2,opt,name=compression,enum=io.itch.wharf.pwr.RecipeHeader_Compression" json:"compression,omitempty"`
	CompressionLevel int32                    `protobuf:"varint,3,opt,name=compressionLevel" json:"compressionLevel,omitempty"`
	FullHashType     HashType                 `protobuf:"varint,4,opt,name=fullHashType,enum=io.itch.wharf.pwr.HashType" json:"fullHashType,omitempty"`
}

func (m *RecipeHeader) Reset()                    { *m = RecipeHeader{} }
func (m *RecipeHeader) String() string            { return proto.CompactTextString(m) }
func (*RecipeHeader) ProtoMessage()               {}
func (*RecipeHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RepoInfo struct {
	NumBlocks int64               `protobuf:"varint,16,opt,name=numBlocks" json:"numBlocks,omitempty"`
	Dirs      []*RepoInfo_Dir     `protobuf:"bytes,1,rep,name=dirs" json:"dirs,omitempty"`
	Files     []*RepoInfo_File    `protobuf:"bytes,2,rep,name=files" json:"files,omitempty"`
	Symlinks  []*RepoInfo_Symlink `protobuf:"bytes,3,rep,name=symlinks" json:"symlinks,omitempty"`
}

func (m *RepoInfo) Reset()                    { *m = RepoInfo{} }
func (m *RepoInfo) String() string            { return proto.CompactTextString(m) }
func (*RepoInfo) ProtoMessage()               {}
func (*RepoInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RepoInfo) GetDirs() []*RepoInfo_Dir {
	if m != nil {
		return m.Dirs
	}
	return nil
}

func (m *RepoInfo) GetFiles() []*RepoInfo_File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *RepoInfo) GetSymlinks() []*RepoInfo_Symlink {
	if m != nil {
		return m.Symlinks
	}
	return nil
}

type RepoInfo_Dir struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Mode uint32 `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
}

func (m *RepoInfo_Dir) Reset()                    { *m = RepoInfo_Dir{} }
func (m *RepoInfo_Dir) String() string            { return proto.CompactTextString(m) }
func (*RepoInfo_Dir) ProtoMessage()               {}
func (*RepoInfo_Dir) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type RepoInfo_File struct {
	Path          string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Mode          uint32 `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
	Size          int64  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	BlockIndex    int64  `protobuf:"varint,4,opt,name=blockIndex" json:"blockIndex,omitempty"`
	BlockIndexEnd int64  `protobuf:"varint,5,opt,name=blockIndexEnd" json:"blockIndexEnd,omitempty"`
}

func (m *RepoInfo_File) Reset()                    { *m = RepoInfo_File{} }
func (m *RepoInfo_File) String() string            { return proto.CompactTextString(m) }
func (*RepoInfo_File) ProtoMessage()               {}
func (*RepoInfo_File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

type RepoInfo_Symlink struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Mode uint32 `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
	Dest string `protobuf:"bytes,3,opt,name=dest" json:"dest,omitempty"`
}

func (m *RepoInfo_Symlink) Reset()                    { *m = RepoInfo_Symlink{} }
func (m *RepoInfo_Symlink) String() string            { return proto.CompactTextString(m) }
func (*RepoInfo_Symlink) ProtoMessage()               {}
func (*RepoInfo_Symlink) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 2} }

type RsyncSignatureHeader struct {
	BlockCount uint64   `protobuf:"varint,1,opt,name=blockCount" json:"blockCount,omitempty"`
	HashType   HashType `protobuf:"varint,2,opt,name=hashType,enum=io.itch.wharf.pwr.HashType" json:"hashType,omitempty"`
}

func (m *RsyncSignatureHeader) Reset()                    { *m = RsyncSignatureHeader{} }
func (m *RsyncSignatureHeader) String() string            { return proto.CompactTextString(m) }
func (*RsyncSignatureHeader) ProtoMessage()               {}
func (*RsyncSignatureHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type RsyncBlockHash struct {
	Index      uint64 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	StrongHash []byte `protobuf:"bytes,2,opt,name=strongHash,proto3" json:"strongHash,omitempty"`
	WeakHash   uint32 `protobuf:"varint,3,opt,name=weakHash" json:"weakHash,omitempty"`
}

func (m *RsyncBlockHash) Reset()                    { *m = RsyncBlockHash{} }
func (m *RsyncBlockHash) String() string            { return proto.CompactTextString(m) }
func (*RsyncBlockHash) ProtoMessage()               {}
func (*RsyncBlockHash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RsyncOp struct {
	Type          RsyncOp_Type `protobuf:"varint,1,opt,name=type,enum=io.itch.wharf.pwr.RsyncOp_Type" json:"type,omitempty"`
	BlockIndex    uint64       `protobuf:"varint,2,opt,name=blockIndex" json:"blockIndex,omitempty"`
	BlockIndexEnd uint64       `protobuf:"varint,3,opt,name=blockIndexEnd" json:"blockIndexEnd,omitempty"`
	Data          []byte       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *RsyncOp) Reset()                    { *m = RsyncOp{} }
func (m *RsyncOp) String() string            { return proto.CompactTextString(m) }
func (*RsyncOp) ProtoMessage()               {}
func (*RsyncOp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Hash struct {
	Type     HashType `protobuf:"varint,1,opt,name=type,enum=io.itch.wharf.pwr.HashType" json:"type,omitempty"`
	Contents []byte   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (m *Hash) Reset()                    { *m = Hash{} }
func (m *Hash) String() string            { return proto.CompactTextString(m) }
func (*Hash) ProtoMessage()               {}
func (*Hash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*RecipeHeader)(nil), "io.itch.wharf.pwr.RecipeHeader")
	proto.RegisterType((*RepoInfo)(nil), "io.itch.wharf.pwr.RepoInfo")
	proto.RegisterType((*RepoInfo_Dir)(nil), "io.itch.wharf.pwr.RepoInfo.Dir")
	proto.RegisterType((*RepoInfo_File)(nil), "io.itch.wharf.pwr.RepoInfo.File")
	proto.RegisterType((*RepoInfo_Symlink)(nil), "io.itch.wharf.pwr.RepoInfo.Symlink")
	proto.RegisterType((*RsyncSignatureHeader)(nil), "io.itch.wharf.pwr.RsyncSignatureHeader")
	proto.RegisterType((*RsyncBlockHash)(nil), "io.itch.wharf.pwr.RsyncBlockHash")
	proto.RegisterType((*RsyncOp)(nil), "io.itch.wharf.pwr.RsyncOp")
	proto.RegisterType((*Hash)(nil), "io.itch.wharf.pwr.Hash")
	proto.RegisterEnum("io.itch.wharf.pwr.HashType", HashType_name, HashType_value)
	proto.RegisterEnum("io.itch.wharf.pwr.RecipeHeader_Version", RecipeHeader_Version_name, RecipeHeader_Version_value)
	proto.RegisterEnum("io.itch.wharf.pwr.RecipeHeader_Compression", RecipeHeader_Compression_name, RecipeHeader_Compression_value)
	proto.RegisterEnum("io.itch.wharf.pwr.RsyncOp_Type", RsyncOp_Type_name, RsyncOp_Type_value)
}

var fileDescriptor0 = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x4f, 0x4f, 0xdb, 0x4e,
	0x10, 0xc5, 0xb1, 0x43, 0xc2, 0x24, 0xf0, 0x33, 0xfb, 0xe3, 0x10, 0xa5, 0x55, 0x8b, 0x5c, 0xa4,
	0x22, 0x50, 0x8d, 0x00, 0xf5, 0xcf, 0xad, 0xca, 0x1f, 0xb7, 0x89, 0x20, 0xa4, 0x5a, 0x07, 0x24,
	0x7a, 0x89, 0x4c, 0xb2, 0x21, 0x56, 0x13, 0xaf, 0xe5, 0x75, 0xa0, 0xf4, 0xd6, 0x5b, 0xbf, 0x5c,
	0xcf, 0x3d, 0xf4, 0xcb, 0x74, 0x77, 0x4c, 0x82, 0x53, 0x28, 0xb4, 0xb7, 0xd9, 0xc9, 0x7b, 0x33,
	0x6f, 0xde, 0x8c, 0x03, 0x66, 0x78, 0x19, 0xed, 0x44, 0xac, 0xe7, 0x87, 0xcc, 0x0e, 0x23, 0x1e,
	0x73, 0xb2, 0xea, 0x73, 0xdb, 0x8f, 0x7b, 0x43, 0xfb, 0x72, 0xe8, 0x45, 0x03, 0x5b, 0xfe, 0x6e,
	0x7d, 0xcf, 0x40, 0x91, 0x22, 0xa6, 0xc1, 0xbc, 0x3e, 0x8b, 0x48, 0x05, 0x72, 0x17, 0x2c, 0x12,
	0x3e, 0x0f, 0x4a, 0xda, 0xba, 0xb6, 0xb9, 0xb2, 0xf7, 0xdc, 0xbe, 0xc5, 0xb2, 0xd3, 0x0c, 0xfb,
	0x24, 0x81, 0xd3, 0x29, 0x8f, 0xb4, 0xa0, 0xd0, 0xe3, 0xe3, 0x30, 0x62, 0x02, 0xcb, 0x64, 0xb0,
	0xcc, 0xf6, 0x43, 0x65, 0x6a, 0x37, 0x14, 0x9a, 0xe6, 0x93, 0x2d, 0x30, 0x53, 0xcf, 0x43, 0x76,
	0xc1, 0x46, 0x25, 0x5d, 0xd6, 0xcc, 0xd2, 0x5b, 0x79, 0xf2, 0x16, 0x8a, 0x83, 0xc9, 0x68, 0xd4,
	0xf0, 0xc4, 0xb0, 0x73, 0x15, 0xb2, 0x92, 0x81, 0xbd, 0x1f, 0xdd, 0xd1, 0x7b, 0x0a, 0xa1, 0x73,
	0x04, 0x6b, 0x15, 0x72, 0xd7, 0xf3, 0x90, 0x45, 0xc8, 0x9c, 0xec, 0x9a, 0x0b, 0xd6, 0x36, 0x14,
	0x52, 0xda, 0x88, 0x09, 0xc5, 0xe3, 0xa3, 0x5a, 0xbb, 0xf5, 0x81, 0x3a, 0xae, 0xeb, 0xd4, 0xcd,
	0x05, 0x02, 0xb0, 0x58, 0xa5, 0xed, 0xce, 0x61, 0xd3, 0xd4, 0xac, 0x1f, 0x3a, 0xe4, 0x29, 0x0b,
	0x79, 0x33, 0x18, 0x70, 0xf2, 0x18, 0x96, 0x82, 0xc9, 0xb8, 0x3a, 0xe2, 0xbd, 0x4f, 0xa2, 0x64,
	0x4a, 0x29, 0x3a, 0xbd, 0x49, 0x90, 0x7d, 0x30, 0xfa, 0x7e, 0x24, 0xa4, 0xcd, 0xfa, 0x66, 0x61,
	0xef, 0xe9, 0x9d, 0xfe, 0x24, 0x85, 0xec, 0xba, 0x1f, 0x51, 0x04, 0x93, 0x57, 0x90, 0x1d, 0xf8,
	0x23, 0x26, 0xa4, 0xab, 0x8a, 0xb5, 0x7e, 0x1f, 0xeb, 0x9d, 0x04, 0xd2, 0x04, 0x2e, 0x8d, 0xc9,
	0x8b, 0xab, 0xf1, 0xc8, 0x0f, 0xa4, 0x12, 0x1d, 0xa9, 0xcf, 0xee, 0xa3, 0xba, 0x09, 0x96, 0xce,
	0x48, 0xe5, 0x17, 0xa0, 0x4b, 0x15, 0x84, 0x80, 0x11, 0x7a, 0xf1, 0x10, 0x6f, 0x63, 0x89, 0x62,
	0xac, 0x72, 0x63, 0xde, 0x67, 0xb8, 0xe8, 0x65, 0x8a, 0x71, 0xf9, 0x9b, 0x06, 0x86, 0xea, 0xff,
	0xb7, 0x04, 0x95, 0x13, 0xfe, 0x17, 0x86, 0x9b, 0xd5, 0x29, 0xc6, 0xe4, 0x09, 0xc0, 0x99, 0xf2,
	0xaa, 0x19, 0xf4, 0xd9, 0x67, 0xdc, 0xa5, 0x4e, 0x53, 0x19, 0xb2, 0x01, 0xcb, 0x37, 0x2f, 0x27,
	0xe8, 0x97, 0xb2, 0x08, 0x99, 0x4f, 0x96, 0x1d, 0xc8, 0x5d, 0x8f, 0xf3, 0x2f, 0x62, 0xfa, 0x4c,
	0xc4, 0x28, 0x46, 0xe2, 0x54, 0x6c, 0x71, 0x58, 0xa3, 0xe2, 0x2a, 0xe8, 0xb9, 0xfe, 0x79, 0xe0,
	0xc5, 0x93, 0x68, 0xfa, 0xc1, 0x4c, 0x45, 0xd6, 0xf8, 0x24, 0x88, 0xb1, 0xb2, 0x41, 0x53, 0x19,
	0xf2, 0x1a, 0xf2, 0xc3, 0xe9, 0x39, 0x66, 0x1e, 0x3e, 0xc7, 0x19, 0xd8, 0x3a, 0x83, 0x15, 0x6c,
	0x88, 0xe7, 0xa2, 0x7e, 0x27, 0x6b, 0x90, 0xf5, 0xd1, 0x8a, 0xa4, 0x4b, 0xf2, 0x50, 0x02, 0x44,
	0x1c, 0xf1, 0xe0, 0x5c, 0x61, 0xb0, 0x45, 0x91, 0xa6, 0x32, 0xa4, 0x0c, 0xf9, 0x4b, 0xe6, 0x61,
	0x05, 0x1c, 0x68, 0x99, 0xce, 0xde, 0xd6, 0x4f, 0x0d, 0x72, 0xd8, 0xa4, 0x1d, 0xaa, 0x7b, 0x8c,
	0x95, 0xc8, 0xe4, 0xb3, 0xbf, 0xf3, 0x1e, 0x13, 0xa4, 0x8d, 0x42, 0x11, 0xfc, 0xdb, 0x8a, 0x32,
	0xa9, 0xe9, 0xff, 0xb0, 0x22, 0x1d, 0x21, 0xf3, 0x49, 0xf4, 0xdb, 0x8b, 0x3d, 0x5c, 0x71, 0x91,
	0x62, 0x6c, 0x55, 0xc0, 0x50, 0x7d, 0xc8, 0x12, 0x64, 0xab, 0x87, 0xed, 0xda, 0x81, 0xfc, 0xd0,
	0xfe, 0x83, 0x02, 0x86, 0x5d, 0x5a, 0x39, 0x7a, 0xef, 0x98, 0x1a, 0xc9, 0x83, 0x51, 0xaf, 0x74,
	0x2a, 0x66, 0x86, 0xfc, 0x0f, 0x2b, 0x0d, 0xe7, 0xb4, 0x7b, 0xda, 0x3e, 0xee, 0xd6, 0x9b, 0xf5,
	0x6e, 0xb3, 0x63, 0x7e, 0x35, 0x2d, 0x17, 0x0c, 0x74, 0x60, 0x67, 0x6e, 0xb2, 0x7b, 0xed, 0x4f,
	0xa6, 0x92, 0x96, 0xf5, 0x78, 0x10, 0xb3, 0x20, 0x16, 0xd7, 0x86, 0xce, 0xde, 0x5b, 0x1b, 0x90,
	0x9f, 0xa2, 0x49, 0x0e, 0xf4, 0x56, 0xfd, 0x65, 0xa2, 0xcc, 0x6d, 0x54, 0x0e, 0x1c, 0xf7, 0xb8,
	0xb5, 0xbb, 0xf7, 0xc6, 0xd4, 0xaa, 0xd9, 0x8f, 0xba, 0xac, 0x7b, 0xb6, 0x88, 0x7f, 0xbc, 0xfb,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xad, 0xdc, 0x52, 0xd0, 0x8c, 0x05, 0x00, 0x00,
}
