// Code generated by protoc-gen-go.
// source: pwr/recipe.proto
// DO NOT EDIT!

/*
Package pwr is a generated protocol buffer package.

It is generated from these files:
	pwr/recipe.proto

It has these top-level messages:
	RepoInfo
	RsyncBlock
*/
package pwr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type RsyncBlock_RsyncOpType int32

const (
	RsyncBlock_BLOCK       RsyncBlock_RsyncOpType = 0
	RsyncBlock_BLOCK_RANGE RsyncBlock_RsyncOpType = 1
	RsyncBlock_DATA        RsyncBlock_RsyncOpType = 2
)

var RsyncBlock_RsyncOpType_name = map[int32]string{
	0: "BLOCK",
	1: "BLOCK_RANGE",
	2: "DATA",
}
var RsyncBlock_RsyncOpType_value = map[string]int32{
	"BLOCK":       0,
	"BLOCK_RANGE": 1,
	"DATA":        2,
}

func (x RsyncBlock_RsyncOpType) String() string {
	return proto.EnumName(RsyncBlock_RsyncOpType_name, int32(x))
}
func (RsyncBlock_RsyncOpType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type RepoInfo struct {
	NumBlocks int64               `protobuf:"varint,16,opt,name=numBlocks" json:"numBlocks,omitempty"`
	Dir       []*RepoInfo_Dir     `protobuf:"bytes,1,rep,name=dir" json:"dir,omitempty"`
	File      []*RepoInfo_File    `protobuf:"bytes,2,rep,name=file" json:"file,omitempty"`
	Symlink   []*RepoInfo_Symlink `protobuf:"bytes,3,rep,name=symlink" json:"symlink,omitempty"`
}

func (m *RepoInfo) Reset()                    { *m = RepoInfo{} }
func (m *RepoInfo) String() string            { return proto.CompactTextString(m) }
func (*RepoInfo) ProtoMessage()               {}
func (*RepoInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RepoInfo) GetDir() []*RepoInfo_Dir {
	if m != nil {
		return m.Dir
	}
	return nil
}

func (m *RepoInfo) GetFile() []*RepoInfo_File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *RepoInfo) GetSymlink() []*RepoInfo_Symlink {
	if m != nil {
		return m.Symlink
	}
	return nil
}

type RepoInfo_Dir struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Mode int32  `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
}

func (m *RepoInfo_Dir) Reset()                    { *m = RepoInfo_Dir{} }
func (m *RepoInfo_Dir) String() string            { return proto.CompactTextString(m) }
func (*RepoInfo_Dir) ProtoMessage()               {}
func (*RepoInfo_Dir) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type RepoInfo_File struct {
	Path          string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Mode          int32  `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
	Size          int64  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	BlockIndex    int64  `protobuf:"varint,4,opt,name=blockIndex" json:"blockIndex,omitempty"`
	BlockIndexEnd int64  `protobuf:"varint,5,opt,name=blockIndexEnd" json:"blockIndexEnd,omitempty"`
}

func (m *RepoInfo_File) Reset()                    { *m = RepoInfo_File{} }
func (m *RepoInfo_File) String() string            { return proto.CompactTextString(m) }
func (*RepoInfo_File) ProtoMessage()               {}
func (*RepoInfo_File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type RepoInfo_Symlink struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Mode int32  `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
	Dest string `protobuf:"bytes,3,opt,name=dest" json:"dest,omitempty"`
}

func (m *RepoInfo_Symlink) Reset()                    { *m = RepoInfo_Symlink{} }
func (m *RepoInfo_Symlink) String() string            { return proto.CompactTextString(m) }
func (*RepoInfo_Symlink) ProtoMessage()               {}
func (*RepoInfo_Symlink) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

type RsyncBlock struct {
	Type          RsyncBlock_RsyncOpType `protobuf:"varint,1,opt,name=type,enum=io.itch.wharf.pwr.RsyncBlock_RsyncOpType" json:"type,omitempty"`
	BlockIndex    int32                  `protobuf:"varint,2,opt,name=blockIndex" json:"blockIndex,omitempty"`
	BlockIndexEnd int32                  `protobuf:"varint,3,opt,name=blockIndexEnd" json:"blockIndexEnd,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *RsyncBlock) Reset()                    { *m = RsyncBlock{} }
func (m *RsyncBlock) String() string            { return proto.CompactTextString(m) }
func (*RsyncBlock) ProtoMessage()               {}
func (*RsyncBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*RepoInfo)(nil), "io.itch.wharf.pwr.RepoInfo")
	proto.RegisterType((*RepoInfo_Dir)(nil), "io.itch.wharf.pwr.RepoInfo.Dir")
	proto.RegisterType((*RepoInfo_File)(nil), "io.itch.wharf.pwr.RepoInfo.File")
	proto.RegisterType((*RepoInfo_Symlink)(nil), "io.itch.wharf.pwr.RepoInfo.Symlink")
	proto.RegisterType((*RsyncBlock)(nil), "io.itch.wharf.pwr.RsyncBlock")
	proto.RegisterEnum("io.itch.wharf.pwr.RsyncBlock_RsyncOpType", RsyncBlock_RsyncOpType_name, RsyncBlock_RsyncOpType_value)
}

var fileDescriptor0 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0xfd, 0xca, 0xb4, 0x1f, 0x70, 0xf9, 0x7e, 0xea, 0xac, 0x1a, 0x62, 0x94, 0xa0, 0x8b, 0xba,
	0xb0, 0x46, 0x70, 0xeb, 0x02, 0x04, 0x0d, 0xd1, 0x48, 0x32, 0xb2, 0x72, 0x63, 0x4a, 0x3b, 0x84,
	0x09, 0xd0, 0x4e, 0xda, 0x1a, 0xc4, 0x27, 0xf0, 0xf5, 0xdc, 0xfa, 0x34, 0xce, 0x5c, 0x44, 0x40,
	0x0d, 0xd1, 0xdd, 0xe1, 0xcc, 0x39, 0xf7, 0x9e, 0x7b, 0x28, 0xd8, 0x72, 0x9a, 0x1c, 0x25, 0x3c,
	0x10, 0x92, 0x7b, 0x32, 0x89, 0xb3, 0x98, 0x6e, 0x89, 0xd8, 0x13, 0x59, 0x30, 0xf4, 0xa6, 0x43,
	0x3f, 0x19, 0x78, 0xea, 0xbd, 0xfa, 0x4c, 0xa0, 0xc0, 0xb8, 0x8c, 0x3b, 0xd1, 0x20, 0xa6, 0xdb,
	0x50, 0x8c, 0xee, 0x27, 0xcd, 0x71, 0x1c, 0x8c, 0x52, 0xc7, 0xae, 0x18, 0x2e, 0x61, 0x4b, 0x82,
	0x1e, 0x03, 0x09, 0x45, 0xe2, 0x18, 0x15, 0xe2, 0x96, 0x6a, 0xbb, 0xde, 0xa7, 0x59, 0xde, 0x62,
	0x8e, 0xd7, 0x12, 0x09, 0xd3, 0x5a, 0x7a, 0x02, 0xe6, 0x40, 0x8c, 0xb9, 0x93, 0x43, 0x4f, 0x65,
	0x93, 0xe7, 0x5c, 0xe9, 0x18, 0xaa, 0xe9, 0x29, 0xe4, 0xd3, 0xd9, 0x64, 0x2c, 0xa2, 0x91, 0x43,
	0xd0, 0xb8, 0xb7, 0xc9, 0x78, 0x33, 0x97, 0xb2, 0x85, 0xa7, 0x7c, 0x08, 0x44, 0x05, 0xa0, 0x14,
	0x4c, 0xe9, 0x67, 0x43, 0x95, 0xd7, 0x70, 0x8b, 0x0c, 0xb1, 0xe6, 0x26, 0x71, 0xa8, 0xf3, 0x18,
	0xae, 0xc5, 0x10, 0x97, 0x9f, 0x0c, 0x30, 0xf5, 0xf2, 0xef, 0x1a, 0x34, 0x97, 0x8a, 0x47, 0xae,
	0xb2, 0xe9, 0x82, 0x10, 0xd3, 0x1d, 0x80, 0xbe, 0x6e, 0xa9, 0x13, 0x85, 0xfc, 0xc1, 0x31, 0xf1,
	0x65, 0x85, 0xa1, 0xfb, 0xf0, 0x77, 0xf9, 0xab, 0x1d, 0x85, 0x8e, 0x85, 0x92, 0x75, 0xb2, 0xdc,
	0x86, 0xfc, 0xdb, 0x35, 0x3f, 0x09, 0x13, 0xf2, 0x34, 0xc3, 0x30, 0x4a, 0xa7, 0x71, 0xf5, 0xc5,
	0x00, 0x60, 0xe9, 0x2c, 0x0a, 0xf0, 0x8f, 0x53, 0x75, 0x9a, 0xd9, 0x4c, 0x72, 0x1c, 0xf5, 0xaf,
	0x76, 0xf0, 0x55, 0x97, 0xef, 0xe2, 0x39, 0xec, 0xca, 0x9e, 0x32, 0x30, 0xb4, 0x7d, 0x38, 0x6d,
	0xbe, 0x7b, 0xe3, 0x69, 0x04, 0x25, 0xeb, 0x24, 0xe6, 0xf4, 0x33, 0x1f, 0xab, 0xf9, 0xc3, 0x10,
	0x57, 0xeb, 0x50, 0x5a, 0x59, 0x47, 0x8b, 0x60, 0x35, 0xaf, 0xba, 0x67, 0x97, 0xf6, 0x2f, 0xfa,
	0x1f, 0x4a, 0x08, 0xef, 0x58, 0xe3, 0xfa, 0xa2, 0x6d, 0x1b, 0xb4, 0x00, 0x66, 0xab, 0xd1, 0x6b,
	0xd8, 0xb9, 0xa6, 0x75, 0x4b, 0x54, 0xe4, 0xfe, 0x6f, 0xfc, 0xa2, 0xeb, 0xaf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x2a, 0xd3, 0x6e, 0xe9, 0xe5, 0x02, 0x00, 0x00,
}
