// Code generated by protoc-gen-go.
// source: wire/messages.proto
// DO NOT EDIT!

/*
Package wire is a generated protocol buffer package.

It is generated from these files:
	wire/messages.proto

It has these top-level messages:
	RecipeHeader
	Container
	SignatureHeader
	BlockHash
	SyncHeader
	SyncOp
	Hash
*/
package wire

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type HashType int32

const (
	// librsync default
	HashType_MD5 HashType = 0
	// cf. https://godoc.org/golang.org/x/crypto/sha3
	HashType_SHAKESUM128 HashType = 1
)

var HashType_name = map[int32]string{
	0: "MD5",
	1: "SHAKESUM128",
}
var HashType_value = map[string]int32{
	"MD5":         0,
	"SHAKESUM128": 1,
}

func (x HashType) String() string {
	return proto.EnumName(HashType_name, int32(x))
}
func (HashType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RecipeHeader_Version int32

const (
	RecipeHeader_V1 RecipeHeader_Version = 0
)

var RecipeHeader_Version_name = map[int32]string{
	0: "V1",
}
var RecipeHeader_Version_value = map[string]int32{
	"V1": 0,
}

func (x RecipeHeader_Version) String() string {
	return proto.EnumName(RecipeHeader_Version_name, int32(x))
}
func (RecipeHeader_Version) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type RecipeHeader_Compression int32

const (
	RecipeHeader_UNCOMPRESSED RecipeHeader_Compression = 0
	RecipeHeader_BROTLI       RecipeHeader_Compression = 1
)

var RecipeHeader_Compression_name = map[int32]string{
	0: "UNCOMPRESSED",
	1: "BROTLI",
}
var RecipeHeader_Compression_value = map[string]int32{
	"UNCOMPRESSED": 0,
	"BROTLI":       1,
}

func (x RecipeHeader_Compression) String() string {
	return proto.EnumName(RecipeHeader_Compression_name, int32(x))
}
func (RecipeHeader_Compression) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type SyncOp_Type int32

const (
	SyncOp_BLOCK          SyncOp_Type = 0
	SyncOp_BLOCK_RANGE    SyncOp_Type = 1
	SyncOp_DATA           SyncOp_Type = 2
	SyncOp_HEY_YOU_DID_IT SyncOp_Type = 2049
)

var SyncOp_Type_name = map[int32]string{
	0:    "BLOCK",
	1:    "BLOCK_RANGE",
	2:    "DATA",
	2049: "HEY_YOU_DID_IT",
}
var SyncOp_Type_value = map[string]int32{
	"BLOCK":          0,
	"BLOCK_RANGE":    1,
	"DATA":           2,
	"HEY_YOU_DID_IT": 2049,
}

func (x SyncOp_Type) String() string {
	return proto.EnumName(SyncOp_Type_name, int32(x))
}
func (SyncOp_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type RecipeHeader struct {
	Version          RecipeHeader_Version     `protobuf:"varint,1,opt,name=version,enum=io.itch.wharf.wire.RecipeHeader_Version" json:"version,omitempty"`
	Compression      RecipeHeader_Compression `protobuf:"varint,2,opt,name=compression,enum=io.itch.wharf.wire.RecipeHeader_Compression" json:"compression,omitempty"`
	CompressionLevel int32                    `protobuf:"varint,3,opt,name=compressionLevel" json:"compressionLevel,omitempty"`
}

func (m *RecipeHeader) Reset()                    { *m = RecipeHeader{} }
func (m *RecipeHeader) String() string            { return proto.CompactTextString(m) }
func (*RecipeHeader) ProtoMessage()               {}
func (*RecipeHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Container struct {
	Size     int64                `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	Dirs     []*Container_Dir     `protobuf:"bytes,2,rep,name=dirs" json:"dirs,omitempty"`
	Files    []*Container_File    `protobuf:"bytes,3,rep,name=files" json:"files,omitempty"`
	Symlinks []*Container_Symlink `protobuf:"bytes,4,rep,name=symlinks" json:"symlinks,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Container) GetDirs() []*Container_Dir {
	if m != nil {
		return m.Dirs
	}
	return nil
}

func (m *Container) GetFiles() []*Container_File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Container) GetSymlinks() []*Container_Symlink {
	if m != nil {
		return m.Symlinks
	}
	return nil
}

type Container_Dir struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Mode uint32 `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
}

func (m *Container_Dir) Reset()                    { *m = Container_Dir{} }
func (m *Container_Dir) String() string            { return proto.CompactTextString(m) }
func (*Container_Dir) ProtoMessage()               {}
func (*Container_Dir) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Container_File struct {
	Path       string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Mode       uint32 `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
	Size       int64  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	BlockIndex int64  `protobuf:"varint,4,opt,name=blockIndex" json:"blockIndex,omitempty"`
	BlockSpan  int64  `protobuf:"varint,5,opt,name=blockSpan" json:"blockSpan,omitempty"`
}

func (m *Container_File) Reset()                    { *m = Container_File{} }
func (m *Container_File) String() string            { return proto.CompactTextString(m) }
func (*Container_File) ProtoMessage()               {}
func (*Container_File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

type Container_Symlink struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Mode uint32 `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
	Dest string `protobuf:"bytes,3,opt,name=dest" json:"dest,omitempty"`
}

func (m *Container_Symlink) Reset()                    { *m = Container_Symlink{} }
func (m *Container_Symlink) String() string            { return proto.CompactTextString(m) }
func (*Container_Symlink) ProtoMessage()               {}
func (*Container_Symlink) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 2} }

type SignatureHeader struct {
	BlockCount int64    `protobuf:"varint,1,opt,name=blockCount" json:"blockCount,omitempty"`
	HashType   HashType `protobuf:"varint,2,opt,name=hashType,enum=io.itch.wharf.wire.HashType" json:"hashType,omitempty"`
}

func (m *SignatureHeader) Reset()                    { *m = SignatureHeader{} }
func (m *SignatureHeader) String() string            { return proto.CompactTextString(m) }
func (*SignatureHeader) ProtoMessage()               {}
func (*SignatureHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type BlockHash struct {
	WeakHash   int32  `protobuf:"varint,1,opt,name=weakHash" json:"weakHash,omitempty"`
	StrongHash []byte `protobuf:"bytes,2,opt,name=strongHash,proto3" json:"strongHash,omitempty"`
}

func (m *BlockHash) Reset()                    { *m = BlockHash{} }
func (m *BlockHash) String() string            { return proto.CompactTextString(m) }
func (*BlockHash) ProtoMessage()               {}
func (*BlockHash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SyncHeader struct {
	FileIndex int64 `protobuf:"varint,1,opt,name=fileIndex" json:"fileIndex,omitempty"`
}

func (m *SyncHeader) Reset()                    { *m = SyncHeader{} }
func (m *SyncHeader) String() string            { return proto.CompactTextString(m) }
func (*SyncHeader) ProtoMessage()               {}
func (*SyncHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SyncOp struct {
	Type       SyncOp_Type `protobuf:"varint,1,opt,name=type,enum=io.itch.wharf.wire.SyncOp_Type" json:"type,omitempty"`
	FileIndex  int64       `protobuf:"varint,2,opt,name=fileIndex" json:"fileIndex,omitempty"`
	BlockIndex int64       `protobuf:"varint,3,opt,name=blockIndex" json:"blockIndex,omitempty"`
	BlockSpan  int64       `protobuf:"varint,4,opt,name=blockSpan" json:"blockSpan,omitempty"`
	Data       []byte      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *SyncOp) Reset()                    { *m = SyncOp{} }
func (m *SyncOp) String() string            { return proto.CompactTextString(m) }
func (*SyncOp) ProtoMessage()               {}
func (*SyncOp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Hash struct {
	Type     HashType `protobuf:"varint,1,opt,name=type,enum=io.itch.wharf.wire.HashType" json:"type,omitempty"`
	Contents []byte   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (m *Hash) Reset()                    { *m = Hash{} }
func (m *Hash) String() string            { return proto.CompactTextString(m) }
func (*Hash) ProtoMessage()               {}
func (*Hash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*RecipeHeader)(nil), "io.itch.wharf.wire.RecipeHeader")
	proto.RegisterType((*Container)(nil), "io.itch.wharf.wire.Container")
	proto.RegisterType((*Container_Dir)(nil), "io.itch.wharf.wire.Container.Dir")
	proto.RegisterType((*Container_File)(nil), "io.itch.wharf.wire.Container.File")
	proto.RegisterType((*Container_Symlink)(nil), "io.itch.wharf.wire.Container.Symlink")
	proto.RegisterType((*SignatureHeader)(nil), "io.itch.wharf.wire.SignatureHeader")
	proto.RegisterType((*BlockHash)(nil), "io.itch.wharf.wire.BlockHash")
	proto.RegisterType((*SyncHeader)(nil), "io.itch.wharf.wire.SyncHeader")
	proto.RegisterType((*SyncOp)(nil), "io.itch.wharf.wire.SyncOp")
	proto.RegisterType((*Hash)(nil), "io.itch.wharf.wire.Hash")
	proto.RegisterEnum("io.itch.wharf.wire.HashType", HashType_name, HashType_value)
	proto.RegisterEnum("io.itch.wharf.wire.RecipeHeader_Version", RecipeHeader_Version_name, RecipeHeader_Version_value)
	proto.RegisterEnum("io.itch.wharf.wire.RecipeHeader_Compression", RecipeHeader_Compression_name, RecipeHeader_Compression_value)
	proto.RegisterEnum("io.itch.wharf.wire.SyncOp_Type", SyncOp_Type_name, SyncOp_Type_value)
}

var fileDescriptor0 = []byte{
	// 654 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0xdb, 0x4e, 0xdb, 0x4c,
	0x10, 0xc6, 0xb1, 0x73, 0x9a, 0xe4, 0x07, 0xff, 0xcb, 0x4d, 0x14, 0xa1, 0x1e, 0xac, 0x56, 0x42,
	0xb4, 0x75, 0x0b, 0x08, 0x89, 0x5b, 0x27, 0x76, 0x49, 0xc4, 0x21, 0xd5, 0x3a, 0x20, 0xd1, 0x9b,
	0xc8, 0x38, 0x0b, 0x59, 0x91, 0xd8, 0x96, 0xd7, 0x40, 0xe9, 0x55, 0xfb, 0x02, 0x7d, 0xb2, 0x3e,
	0x4c, 0x1f, 0xa1, 0xbb, 0x6b, 0xc7, 0x98, 0x83, 0xd2, 0xf6, 0x6e, 0x76, 0xf6, 0xfb, 0xbe, 0xf9,
	0x66, 0xc6, 0x6b, 0x58, 0xbd, 0xa1, 0x31, 0x79, 0x3f, 0x23, 0x8c, 0x79, 0x17, 0x84, 0x99, 0x51,
	0x1c, 0x26, 0x21, 0x42, 0x34, 0x34, 0x69, 0xe2, 0x4f, 0xcc, 0x9b, 0x89, 0x17, 0x9f, 0x9b, 0x02,
	0x62, 0xfc, 0x28, 0x41, 0x13, 0x13, 0x9f, 0x46, 0xa4, 0x47, 0xbc, 0x31, 0x89, 0x51, 0x07, 0xaa,
	0xd7, 0x24, 0x66, 0x34, 0x0c, 0x5a, 0xca, 0x0b, 0x65, 0x7d, 0x79, 0x6b, 0xdd, 0x7c, 0x4c, 0x33,
	0x8b, 0x14, 0xf3, 0x24, 0xc5, 0xe3, 0x39, 0x11, 0x1d, 0x41, 0xc3, 0x0f, 0x67, 0x51, 0xcc, 0xcb,
	0x0b, 0x9d, 0x92, 0xd4, 0x79, 0xfb, 0x47, 0x9d, 0xee, 0x1d, 0x07, 0x17, 0x05, 0xd0, 0x06, 0xe8,
	0x85, 0xe3, 0x01, 0xb9, 0x26, 0xd3, 0x96, 0xca, 0x45, 0xcb, 0xf8, 0x51, 0xde, 0xf8, 0x1f, 0xaa,
	0x99, 0x1f, 0x54, 0x81, 0xd2, 0xc9, 0xa6, 0xbe, 0x64, 0xbc, 0x81, 0x46, 0x41, 0x1a, 0xe9, 0xd0,
	0x3c, 0x3e, 0xea, 0x0e, 0x0e, 0x3f, 0x61, 0xc7, 0x75, 0x1d, 0x5b, 0x5f, 0x42, 0x00, 0x95, 0x0e,
	0x1e, 0x0c, 0x0f, 0xfa, 0xba, 0x62, 0xfc, 0x54, 0xa1, 0xde, 0x0d, 0x83, 0xc4, 0xa3, 0x01, 0x9f,
	0x06, 0x02, 0x8d, 0xd1, 0xaf, 0x44, 0x8e, 0x42, 0xc5, 0x32, 0x46, 0x3b, 0xa0, 0x8d, 0x69, 0xcc,
	0x78, 0x5b, 0xea, 0x7a, 0x63, 0xeb, 0xe5, 0x53, 0x6d, 0xe5, 0x02, 0xa6, 0x4d, 0x63, 0x2c, 0xe1,
	0x68, 0x17, 0xca, 0xe7, 0x74, 0x4a, 0x18, 0x77, 0x2e, 0x78, 0xc6, 0x62, 0xde, 0x47, 0x0e, 0xc5,
	0x29, 0x01, 0x59, 0x50, 0x63, 0xb7, 0xb3, 0x29, 0x0d, 0x2e, 0x59, 0x4b, 0x93, 0xe4, 0xd7, 0x8b,
	0xc9, 0x6e, 0x8a, 0xc6, 0x39, 0xad, 0xfd, 0x0e, 0x54, 0xee, 0x44, 0xb4, 0x13, 0x79, 0xc9, 0x44,
	0xb6, 0x53, 0xc7, 0x32, 0x16, 0xb9, 0x59, 0x38, 0x26, 0x72, 0x4b, 0xff, 0x61, 0x19, 0xb7, 0xbf,
	0x29, 0xa0, 0x09, 0x07, 0x7f, 0x4b, 0xc8, 0xe7, 0xa4, 0x16, 0xe6, 0xf4, 0x0c, 0xe0, 0x6c, 0x1a,
	0xfa, 0x97, 0xfd, 0x60, 0x4c, 0xbe, 0x70, 0xe3, 0xe2, 0xa6, 0x90, 0x41, 0x6b, 0x50, 0x97, 0x27,
	0x37, 0xf2, 0x82, 0x56, 0x59, 0x5e, 0xdf, 0x25, 0xda, 0x0e, 0x54, 0xb3, 0x36, 0xfe, 0xc5, 0xc4,
	0x98, 0xb0, 0x44, 0x9a, 0xe0, 0x38, 0x11, 0x1b, 0x97, 0xb0, 0xe2, 0xd2, 0x8b, 0xc0, 0x4b, 0xae,
	0xe2, 0xf9, 0x17, 0x3e, 0xf7, 0xd5, 0x0d, 0xaf, 0x82, 0x24, 0xdb, 0x6c, 0x21, 0xc3, 0x17, 0x55,
	0x9b, 0x78, 0x6c, 0x32, 0xbc, 0x8d, 0x48, 0xf6, 0xe9, 0xae, 0x3d, 0x35, 0xee, 0x5e, 0x86, 0xc1,
	0x39, 0xda, 0xd8, 0x83, 0x7a, 0x47, 0xe8, 0x88, 0x2b, 0xd4, 0x86, 0xda, 0x0d, 0xf1, 0x64, 0x2c,
	0x8b, 0x94, 0x71, 0x7e, 0x16, 0x16, 0x58, 0x12, 0x87, 0xc1, 0x85, 0xbc, 0x15, 0x45, 0x9a, 0xb8,
	0x90, 0x31, 0x36, 0x00, 0xdc, 0xdb, 0xc0, 0xcf, 0x0c, 0xf3, 0x41, 0x89, 0x0f, 0x21, 0x9d, 0x63,
	0xea, 0xf7, 0x2e, 0x61, 0xfc, 0x52, 0xa0, 0x22, 0xc0, 0x83, 0x08, 0x6d, 0x83, 0x96, 0x08, 0xd7,
	0xe9, 0xc3, 0x7d, 0xfe, 0x94, 0xeb, 0x14, 0x69, 0x4a, 0xe3, 0x12, 0x7c, 0x5f, 0xbd, 0xf4, 0x40,
	0xfd, 0xc1, 0x12, 0xd5, 0xc5, 0x4b, 0xd4, 0x1e, 0x2c, 0x51, 0x6e, 0xc4, 0x4b, 0x3c, 0xb9, 0xdd,
	0x26, 0x96, 0xb1, 0x61, 0x81, 0x26, 0xaa, 0xa3, 0x3a, 0x94, 0x3b, 0x07, 0x83, 0xee, 0x3e, 0x7f,
	0x7f, 0x2b, 0xd0, 0x90, 0xe1, 0x08, 0x5b, 0x47, 0x7b, 0x8e, 0xae, 0xa0, 0x1a, 0x68, 0xb6, 0x35,
	0xb4, 0xf4, 0x12, 0x5a, 0x85, 0xe5, 0x9e, 0x73, 0x3a, 0x3a, 0x1d, 0x1c, 0x8f, 0xec, 0xbe, 0x3d,
	0xea, 0x0f, 0xf5, 0xef, 0xba, 0x31, 0x04, 0x4d, 0x8e, 0xf1, 0xc3, 0xbd, 0x7e, 0x17, 0x6f, 0x29,
	0x6d, 0x96, 0x2f, 0xc5, 0xe7, 0xcf, 0x84, 0x04, 0x09, 0xcb, 0xc6, 0x9e, 0x9f, 0x37, 0x5e, 0x41,
	0x6d, 0x8e, 0x46, 0x55, 0x50, 0x0f, 0xed, 0x9d, 0xd4, 0x9a, 0xdb, 0xb3, 0xf6, 0x1d, 0xf7, 0xf8,
	0x70, 0x73, 0x6b, 0x57, 0x57, 0x3a, 0x95, 0xcf, 0x9a, 0x10, 0x3e, 0xab, 0xc8, 0x7f, 0xea, 0xf6,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x40, 0x38, 0x4b, 0x6a, 0x05, 0x00, 0x00,
}
