// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: wire/wire.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Number        int64                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_wire_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_wire_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_wire_wire_proto_rawDescGZIP(), []int{0}
}

func (x *Sample) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Sample) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Sample) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

var File_wire_wire_proto protoreflect.FileDescriptor

const file_wire_wire_proto_rawDesc = "" +
	"\n" +
	"\x0fwire/wire.proto\x12\x12io.itch.wharf.wire\"F\n" +
	"\x06Sample\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x03R\x06number\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eofB\x1eZ\x1cgithub.com/itchio/wharf/wireb\x06proto3"

var (
	file_wire_wire_proto_rawDescOnce sync.Once
	file_wire_wire_proto_rawDescData []byte
)

func file_wire_wire_proto_rawDescGZIP() []byte {
	file_wire_wire_proto_rawDescOnce.Do(func() {
		file_wire_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_wire_proto_rawDesc), len(file_wire_wire_proto_rawDesc)))
	})
	return file_wire_wire_proto_rawDescData
}

var file_wire_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wire_wire_proto_goTypes = []any{
	(*Sample)(nil), // 0: io.itch.wharf.wire.Sample
}
var file_wire_wire_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wire_wire_proto_init() }
func file_wire_wire_proto_init() {
	if File_wire_wire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_wire_proto_rawDesc), len(file_wire_wire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_wire_proto_goTypes,
		DependencyIndexes: file_wire_wire_proto_depIdxs,
		MessageInfos:      file_wire_wire_proto_msgTypes,
	}.Build()
	File_wire_wire_proto = out.File
	file_wire_wire_proto_goTypes = nil
	file_wire_wire_proto_depIdxs = nil
}
